## makeCacheMatrix creates a function to cache, or store, a calculaiton for later use
## The function takes a matrix as an input, and outputs a list.  cacheSolve takes
## the list generated by the makeCacheMatrix function and outputs the vlaue of the
## inverse of the input matrix.  It then stores the solution for later use if the
## input matrix is input again.

## The list starts with set, which is another function, taking the matrix input and
## saving it to x and creating M to null.  The <<- allows values to be set in an environment
## other than the one it is created in.
## Next is get, which is a function wiht no inputs and gives you the input matrix
## setSolve is the function that applies solve to the input matrix and 'sets the value
## getSolve is a function that returns the value of m, which is initialized to null

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setSolve <- function(solve) m <<- solve
  getSolve <- function() m
  list(set = set, get = get,
       setSolve = setSolve,
       getSolve = getSolve)
}


## cacheSolve takes the list generated from makeCacheMatrix as input
## m is set to the setSolve value, and if m is null, then the function
## applies the solve function the the matrix in the 'get' item in the list.
## setSolve is set to m and m is output.  If the function is called again
## m is not null, and the function outputs the message "getting cached data"
## and outputs the current value of m, wihtout having to do the computation
##again.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getSolve()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setSolve(m)
  m
}